### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by ivargrimstad**
Update versions for Jakarta EE 11 M2 release

### CODE REVIEW

**Comment by pnicolucci** [comment]
Hi @ivargrimstad , why the proposal for update here? Jakarta Tags isn't updating at all for Jakarta EE11.

**Comment by arjantijms** [comment]
> > Hi @ivargrimstad , why the proposal for update here? Jakarta Tags isn't updating at all for Jakarta EE11.
> 
> It has dependencies on older versions and including it as it is will cause it to fail in an OSGI container. So only a service release is needed. @arjantijms Did I get it right?

Yes, that's right.

So specifically it depends in Expression Language 5. In Jakarta EE 11 Expression Language updated to Expression Language 6. This means Jakarta Tags currently has a guard in its MANIFEST.MF that says "no version higher than 5 is allowed". On OSGi containers this guard is honoured, so the OSGi container will panic and halt when it only finds a version 6.

**Comment by pnicolucci** [comment]
@arjantijms , so should this PR be against the `3.x` branch rather than `master`? 

Also, once I build using this PR I see that not only does the upper limit for the `import` change but also the lower limit. For example:

Current MANIFEST.MF lists: `Import-Package: jakarta.el;version="[5.0,6)"`
With this PR the MANIFEST.MF lists: `Import-Package: jakarta.el;version="[6.0,7)"`

In reality, we need `Import-Package: jakarta.el;version="[5.0,7)"` This would allow the service release to work with either EE10 or EE11.

I believe this is a time when these imports will need to be explicitly defined in the MANIFEST.MF, using `<Import-Package/>` with the `maven-bundle-plugin`.

Something such as:

```
                        <Import-Package>
                            jakarta.el;version="[5.0.0, 7.0.0)",
                            jakarta.servlet.jsp;version="[3.1.0, 5.0.0)",
                            *
                        </Import-Package>
```

I don't think anything is necessary for Servlet, since the MANIFEST.mf already shows:

`jakarta.servlet;version="[6.0,7)"` which would cover Servlet 6.0 (EE10) and Servlet 6.1 (EE11).

**Comment by ivargrimstad** [comment]
Thanks for the explanation! I'll close this PR and Arjan can open a new to the 3-branch

**Pull request closed without merging**
